DROP TABLE request_log;

CREATE TABLE IF NOT EXISTS request_log (
    request_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_state varchar,
    request_content text,
    request_date timestamp);

-- CREATE TABLE input_data (
--     input_id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--     input_images bytea,
--     input_parameters text,
--     input_date timestamp);

DROP TABLE input_data;

CREATE TABLE IF NOT EXISTS input_data (
    input_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    input_parameters text,
    input_date timestamp);

DROP TABLE access_log;

CREATE TABLE IF NOT EXISTS access_log (
    access_id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    access_ip varchar,
    access_method varchar,
    access_content text,
    access_date timestamp);